### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by abe520** [Sergei-Korneev/Joplin-mobile-to-Obsidian-md#1]
![cmd-20220904-1550-rp9](https://user-images.githubusercontent.com/9929511/188303314-f50a5cb1-8ccf-476c-97e2-eae92d3a7ea2.png)
![Uploading explorer-20220904-1552-REw.png…]()

**Comment by Sergei-Korneev** [comment]
Hola, Windows user;) Just fixed the code so now it should work on Windows too. I just tested it on windows server '19 + python 3.10.6.  + joplin Android 1.0.331-2.8.1 So, you can give it another try.  

![изображение](https://user-images.githubusercontent.com/60899505/188323001-6c064faf-d0a5-4b27-928e-93284e6e3d96.png)
![изображение](https://user-images.githubusercontent.com/60899505/188323013-897a0ceb-978e-4bd7-a65a-f8dfaa50abab.png)
![изображение](https://user-images.githubusercontent.com/60899505/188323039-fe973668-f628-41cd-8789-c2147b0894ca.png)

**Comment by Sergei-Korneev** [comment]
Maybe I will add directory structure support also, if you guys need it) I wrote this script for personal use and I did not particularly need that.

**Comment by Sergei-Korneev** [comment]
Done

[#a37562e5249f6e691aa07b9c13a295da9e228389](https://github.com/Sergei-Korneev/Joplin-mobile-to-Obsidian-md/commit/a37562e5249f6e691aa07b9c13a295da9e228389)
