### ISSUE TITLE
Notes with forward slash in title

### ISSUE THREAD

**Issue by powerarmorpatch** [Sergei-Korneev/Joplin-mobile-to-Obsidian-md#3]
Hi! App can't handle notes with forward slash in title:
`Welcome! (Desktop)      ds3vXEP/CfrirZQNPCd4KCXkvLeCb7h0PX+IuYkQqAE=
Traceback (most recent call last):
  File "/home/dmitry/Joplin-mobile-to-Obsidian-md-main/convert.py", line 82, in <module>
    main()
  File "/home/dmitry/Joplin-mobile-to-Obsidian-md-main/convert.py", line 73, in main
    note_file=codecs.open(os.path.join(expath, folders[row[2]], row[0] + ".md"), "w", "utf-8")           
  File "/usr/lib/python3.10/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'JoplinExport/Obsidian/Welcome! (Desktop)/ds3vXEP/CfrirZQNPCd4KCXkvLeCb7h0PX+IuYkQqAE=.md'`

**Comment by Sergei-Korneev** [comment]
Hi. Thanks. Yeah, unfortunately some characters are forbidden in file names. In Windows file system (ntfs) there are even more more of them. I do not know any other  way to fix it than to replace those symbols in the output filename, which I did in this commit.  https://github.com/Sergei-Korneev/Joplin-mobile-to-Obsidian-md/commit/7594cd7b334ed05c2b5e9dd0914f707eed2255ae
Now it  looks like this
![image](https://user-images.githubusercontent.com/60899505/205439748-9a05b8fd-50d8-4b65-b724-d4d380d4568c.png)

![image](https://user-images.githubusercontent.com/60899505/205439788-5f754bcc-55f5-4c57-bfba-875e2607cf64.png)

Good luck
