### ISSUE TITLE
Desktop version with multi-level folder structure

### ISSUE THREAD

**Issue by abe520** [Sergei-Korneev/Joplin-mobile-to-Obsidian-md#5]
Desktop version with multi-level folder structure

Notes from web clippings have the same title, page 1 and page 2 and page 3.Can it be renamed automatically?

**Comment by Sergei-Korneev** [comment]
@abe520  send the compressed profile with multi-level folder stricture and note title duplicates  (if joplin allows this O o)

**Comment by abe520** [comment]
[test.zip](https://github.com/Sergei-Korneev/Joplin-mobile-to-Obsidian-md/files/10380283/test.zip)
desktop

**Comment by Sergei-Korneev** [comment]
Hi. Just added desktop support. You can test it.

**Comment by Sergei-Korneev** [comment]
in case of duplicates https://github.com/Sergei-Korneev/Joplin-to-Obsidian-md/commit/aec63cd37d1c154c700c8f0ba72735eae9b19627

**Comment by Sergei-Korneev** [comment]
https://github.com/Sergei-Korneev/Joplin-to-Obsidian-md/commit/4dd22cacf880be9d422d7630f87ef7852f321ce9

**Comment by abe520** [comment]
![image](https://user-images.githubusercontent.com/9929511/212318335-ea5e0f01-949a-44b2-9cf2-ed226f6ddd9b.png)

lost pictures
Only tested in win
[t2.zip](https://github.com/Sergei-Korneev/Joplin-to-Obsidian-md/files/10411379/t2.zip)

**Comment by Sergei-Korneev** [comment]
You are good tester , mate. But I just checked for example 358db674150b4df0a329f1287c9468b5 1642792919-eb85f580700d648aed69627166c0906b.jpg  they are not present in the source folder you have sent me
![image](https://user-images.githubusercontent.com/60899505/212321890-ccbaf364-8b54-4996-90f3-8c9559b2a09f.png)

**Comment by Sergei-Korneev** [comment]
And I do not know where to get them , sorry ;)

**Comment by Sergei-Korneev** [comment]
At first I thought the files were missed from the resources folder.... You know, mate, we could be  a good team as a dev + tester. :) I have changed search pattern. Now it works on some samples you have send me.

**Comment by abe520** [comment]
Optimizing Table Requirements
![image](https://user-images.githubusercontent.com/9929511/213801051-8c204a96-2cad-4b6a-98d2-c1c1272db99a.png)
![image](https://user-images.githubusercontent.com/9929511/213801071-9451a67d-7888-4845-b04b-e7f4efd7ec25.png)
[test3.zip](https://github.com/Sergei-Korneev/Joplin-to-Obsidian-md/files/10470075/test3.zip)
